-- Migration 000021: reserved for the original Phase 5 analytics views.
--
-- The historical implementation referenced columns and joins that no longer
-- exist in the normalized schema (for example behavior_notes.category and a
-- class_id-to-term_id join). Keeping that SQL here made a clean database
-- migration fail before the corrected migration could run. The replacement
-- views are created by 000026_correct_analytics_mvs after all current schema
-- migrations have been applied.
