name: ci

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Cache Go
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Install tools
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
      - name: Lint & Vet
        run: |
          go vet ./...
      - name: Test
        run: |
          go test -v ./...
      - name: Build
        run: |
          go build -v ./cmd/api-gateway
