name: shadow-compare

on:
  schedule:
    - cron: '30 2 * * *'
  workflow_dispatch:

jobs:
  shadow:
    runs-on: ubuntu-latest
    env:
      LEGACY_BASE_URL: ${{ secrets.LEGACY_BASE_URL }}
      GO_BASE_URL: ${{ secrets.GO_BASE_URL }}
    steps:
      - name: Skip if base URLs are not configured
        if: ${{ env.LEGACY_BASE_URL == '' || env.GO_BASE_URL == '' }}
        run: |
          echo "LEGACY_BASE_URL and GO_BASE_URL secrets are required to run shadow compare."
          exit 0
      - uses: actions/checkout@v4
        if: ${{ env.LEGACY_BASE_URL != '' && env.GO_BASE_URL != '' }}
      - uses: actions/setup-go@v5
        if: ${{ env.LEGACY_BASE_URL != '' && env.GO_BASE_URL != '' }}
        with:
          go-version: '1.21'
      - name: Execute shadow compare
        if: ${{ env.LEGACY_BASE_URL != '' && env.GO_BASE_URL != '' }}
        run: go run ./scripts/shadow_compare --legacy-base "$LEGACY_BASE_URL" --go-base "$GO_BASE_URL"
